//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class BoolMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/Bool";
        public override string RosMessageName => k_RosMessageName;

        public bool value;

        public BoolMsg()
        {
            this.value = false;
        }

        public BoolMsg(bool value)
        {
            this.value = value;
        }

        public static BoolMsg Deserialize(MessageDeserializer deserializer) => new BoolMsg(deserializer);

        private BoolMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "BoolMsg: " +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
