//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class CValueMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/CValue";
        public override string RosMessageName => k_RosMessageName;

        public float c;

        public CValueMsg()
        {
            this.c = 0.0f;
        }

        public CValueMsg(float c)
        {
            this.c = c;
        }

        public static CValueMsg Deserialize(MessageDeserializer deserializer) => new CValueMsg(deserializer);

        private CValueMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.c);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.c);
        }

        public override string ToString()
        {
            return "CValueMsg: " +
            "\nc: " + c.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
