//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class DataToUnityMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/dataToUnity";
        public override string RosMessageName => k_RosMessageName;

        public float data_vel_art;
        public float data_force;
        public float data_position;

        public DataToUnityMsg()
        {
            this.data_vel_art = 0.0f;
            this.data_force = 0.0f;
            this.data_position = 0.0f;
        }

        public DataToUnityMsg(float data_vel_art, float data_force, float data_position)
        {
            this.data_vel_art = data_vel_art;
            this.data_force = data_force;
            this.data_position = data_position;
        }

        public static DataToUnityMsg Deserialize(MessageDeserializer deserializer) => new DataToUnityMsg(deserializer);

        private DataToUnityMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data_vel_art);
            deserializer.Read(out this.data_force);
            deserializer.Read(out this.data_position);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.data_vel_art);
            serializer.Write(this.data_force);
            serializer.Write(this.data_position);
        }

        public override string ToString()
        {
            return "DataToUnityMsg: " +
            "\ndata_vel_art: " + data_vel_art.ToString() +
            "\ndata_force: " + data_force.ToString() +
            "\ndata_position: " + data_position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
