//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class FloatMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/Float";
        public override string RosMessageName => k_RosMessageName;

        public float value;

        public FloatMsg()
        {
            this.value = 0.0f;
        }

        public FloatMsg(float value)
        {
            this.value = value;
        }

        public static FloatMsg Deserialize(MessageDeserializer deserializer) => new FloatMsg(deserializer);

        private FloatMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "FloatMsg: " +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
