//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class IntMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/Int";
        public override string RosMessageName => k_RosMessageName;

        public int value;

        public IntMsg()
        {
            this.value = 0;
        }

        public IntMsg(int value)
        {
            this.value = value;
        }

        public static IntMsg Deserialize(MessageDeserializer deserializer) => new IntMsg(deserializer);

        private IntMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "IntMsg: " +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
