//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class JointPosMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/JointPos";
        public override string RosMessageName => k_RosMessageName;

        public float[] pos;

        public JointPosMsg()
        {
            this.pos = new float[6];
        }

        public JointPosMsg(float[] pos)
        {
            this.pos = pos;
        }

        public static JointPosMsg Deserialize(MessageDeserializer deserializer) => new JointPosMsg(deserializer);

        private JointPosMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pos, sizeof(float), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pos);
        }

        public override string ToString()
        {
            return "JointPosMsg: " +
            "\npos: " + System.String.Join(", ", pos.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
