//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class JointVelMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/JointVel";
        public override string RosMessageName => k_RosMessageName;

        public float[] vel;

        public JointVelMsg()
        {
            this.vel = new float[6];
        }

        public JointVelMsg(float[] vel)
        {
            this.vel = vel;
        }

        public static JointVelMsg Deserialize(MessageDeserializer deserializer) => new JointVelMsg(deserializer);

        private JointVelMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.vel, sizeof(float), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.vel);
        }

        public override string ToString()
        {
            return "JointVelMsg: " +
            "\nvel: " + System.String.Join(", ", vel.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
