//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class List6floatMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/List6float";
        public override string RosMessageName => k_RosMessageName;

        public float[] list;

        public List6floatMsg()
        {
            this.list = new float[6];
        }

        public List6floatMsg(float[] list)
        {
            this.list = list;
        }

        public static List6floatMsg Deserialize(MessageDeserializer deserializer) => new List6floatMsg(deserializer);

        private List6floatMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.list, sizeof(float), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.list);
        }

        public override string ToString()
        {
            return "List6floatMsg: " +
            "\nlist: " + System.String.Join(", ", list.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
