//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class PlaneOfWorkMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/PlaneOfWork";
        public override string RosMessageName => k_RosMessageName;

        public int plane;

        public PlaneOfWorkMsg()
        {
            this.plane = 0;
        }

        public PlaneOfWorkMsg(int plane)
        {
            this.plane = plane;
        }

        public static PlaneOfWorkMsg Deserialize(MessageDeserializer deserializer) => new PlaneOfWorkMsg(deserializer);

        private PlaneOfWorkMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.plane);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.plane);
        }

        public override string ToString()
        {
            return "PlaneOfWorkMsg: " +
            "\nplane: " + plane.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
