//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class PosQuatMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/PosQuat";
        public override string RosMessageName => k_RosMessageName;

        public float p_x;
        public float p_y;
        public float p_z;
        public float q_w;
        public float q_x;
        public float q_y;
        public float q_z;

        public PosQuatMsg()
        {
            this.p_x = 0.0f;
            this.p_y = 0.0f;
            this.p_z = 0.0f;
            this.q_w = 0.0f;
            this.q_x = 0.0f;
            this.q_y = 0.0f;
            this.q_z = 0.0f;
        }

        public PosQuatMsg(float p_x, float p_y, float p_z, float q_w, float q_x, float q_y, float q_z)
        {
            this.p_x = p_x;
            this.p_y = p_y;
            this.p_z = p_z;
            this.q_w = q_w;
            this.q_x = q_x;
            this.q_y = q_y;
            this.q_z = q_z;
        }

        public static PosQuatMsg Deserialize(MessageDeserializer deserializer) => new PosQuatMsg(deserializer);

        private PosQuatMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.p_x);
            deserializer.Read(out this.p_y);
            deserializer.Read(out this.p_z);
            deserializer.Read(out this.q_w);
            deserializer.Read(out this.q_x);
            deserializer.Read(out this.q_y);
            deserializer.Read(out this.q_z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.p_x);
            serializer.Write(this.p_y);
            serializer.Write(this.p_z);
            serializer.Write(this.q_w);
            serializer.Write(this.q_x);
            serializer.Write(this.q_y);
            serializer.Write(this.q_z);
        }

        public override string ToString()
        {
            return "PosQuatMsg: " +
            "\np_x: " + p_x.ToString() +
            "\np_y: " + p_y.ToString() +
            "\np_z: " + p_z.ToString() +
            "\nq_w: " + q_w.ToString() +
            "\nq_x: " + q_x.ToString() +
            "\nq_y: " + q_y.ToString() +
            "\nq_z: " + q_z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
