//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class PosURMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/PosUR";
        public override string RosMessageName => k_RosMessageName;

        public float ini_pos_x;
        public float ini_pos_y;
        public float ini_pos_z;
        public float pos_x;
        public float pos_y;
        public float pos_z;

        public PosURMsg()
        {
            this.ini_pos_x = 0.0f;
            this.ini_pos_y = 0.0f;
            this.ini_pos_z = 0.0f;
            this.pos_x = 0.0f;
            this.pos_y = 0.0f;
            this.pos_z = 0.0f;
        }

        public PosURMsg(float ini_pos_x, float ini_pos_y, float ini_pos_z, float pos_x, float pos_y, float pos_z)
        {
            this.ini_pos_x = ini_pos_x;
            this.ini_pos_y = ini_pos_y;
            this.ini_pos_z = ini_pos_z;
            this.pos_x = pos_x;
            this.pos_y = pos_y;
            this.pos_z = pos_z;
        }

        public static PosURMsg Deserialize(MessageDeserializer deserializer) => new PosURMsg(deserializer);

        private PosURMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ini_pos_x);
            deserializer.Read(out this.ini_pos_y);
            deserializer.Read(out this.ini_pos_z);
            deserializer.Read(out this.pos_x);
            deserializer.Read(out this.pos_y);
            deserializer.Read(out this.pos_z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ini_pos_x);
            serializer.Write(this.ini_pos_y);
            serializer.Write(this.ini_pos_z);
            serializer.Write(this.pos_x);
            serializer.Write(this.pos_y);
            serializer.Write(this.pos_z);
        }

        public override string ToString()
        {
            return "PosURMsg: " +
            "\nini_pos_x: " + ini_pos_x.ToString() +
            "\nini_pos_y: " + ini_pos_y.ToString() +
            "\nini_pos_z: " + ini_pos_z.ToString() +
            "\npos_x: " + pos_x.ToString() +
            "\npos_y: " + pos_y.ToString() +
            "\npos_z: " + pos_z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
