//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class StartCalibMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/StartCalib";
        public override string RosMessageName => k_RosMessageName;

        public bool startCalib;

        public StartCalibMsg()
        {
            this.startCalib = false;
        }

        public StartCalibMsg(bool startCalib)
        {
            this.startCalib = startCalib;
        }

        public static StartCalibMsg Deserialize(MessageDeserializer deserializer) => new StartCalibMsg(deserializer);

        private StartCalibMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.startCalib);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.startCalib);
        }

        public override string ToString()
        {
            return "StartCalibMsg: " +
            "\nstartCalib: " + startCalib.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
