//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class StringMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/String";
        public override string RosMessageName => k_RosMessageName;

        public string value;

        public StringMsg()
        {
            this.value = "";
        }

        public StringMsg(string value)
        {
            this.value = value;
        }

        public static StringMsg Deserialize(MessageDeserializer deserializer) => new StringMsg(deserializer);

        private StringMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "StringMsg: " +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
