//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class TCPPosSubMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/TCPPosSub";
        public override string RosMessageName => k_RosMessageName;

        public float[] pos;

        public TCPPosSubMsg()
        {
            this.pos = new float[3];
        }

        public TCPPosSubMsg(float[] pos)
        {
            this.pos = pos;
        }

        public static TCPPosSubMsg Deserialize(MessageDeserializer deserializer) => new TCPPosSubMsg(deserializer);

        private TCPPosSubMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pos, sizeof(float), 3);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pos);
        }

        public override string ToString()
        {
            return "TCPPosSubMsg: " +
            "\npos: " + System.String.Join(", ", pos.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
