//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class TimestampMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/Timestamp";
        public override string RosMessageName => k_RosMessageName;

        public float times;

        public TimestampMsg()
        {
            this.times = 0.0f;
        }

        public TimestampMsg(float times)
        {
            this.times = times;
        }

        public static TimestampMsg Deserialize(MessageDeserializer deserializer) => new TimestampMsg(deserializer);

        private TimestampMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.times);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.times);
        }

        public override string ToString()
        {
            return "TimestampMsg: " +
            "\ntimes: " + times.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
