//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class TypeControlMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/TypeControl";
        public override string RosMessageName => k_RosMessageName;

        public string type;

        public TypeControlMsg()
        {
            this.type = "";
        }

        public TypeControlMsg(string type)
        {
            this.type = type;
        }

        public static TypeControlMsg Deserialize(MessageDeserializer deserializer) => new TypeControlMsg(deserializer);

        private TypeControlMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.type);
        }

        public override string ToString()
        {
            return "TypeControlMsg: " +
            "\ntype: " + type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
