//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class UnityPositionMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/UnityPosition";
        public override string RosMessageName => k_RosMessageName;

        public float pos_x;
        public float pos_y;
        public float pos_z;
        public float times;
        public float[] pos;
        public float[] vel;
        public float[] force;
        public float[] pos_art;
        public float[] vel_art;

        public UnityPositionMsg()
        {
            this.pos_x = 0.0f;
            this.pos_y = 0.0f;
            this.pos_z = 0.0f;
            this.times = 0.0f;
            this.pos = new float[3];
            this.vel = new float[3];
            this.force = new float[3];
            this.pos_art = new float[6];
            this.vel_art = new float[6];
        }

        public UnityPositionMsg(float pos_x, float pos_y, float pos_z, float times, float[] pos, float[] vel, float[] force, float[] pos_art, float[] vel_art)
        {
            this.pos_x = pos_x;
            this.pos_y = pos_y;
            this.pos_z = pos_z;
            this.times = times;
            this.pos = pos;
            this.vel = vel;
            this.force = force;
            this.pos_art = pos_art;
            this.vel_art = vel_art;
        }

        public static UnityPositionMsg Deserialize(MessageDeserializer deserializer) => new UnityPositionMsg(deserializer);

        private UnityPositionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pos_x);
            deserializer.Read(out this.pos_y);
            deserializer.Read(out this.pos_z);
            deserializer.Read(out this.times);
            deserializer.Read(out this.pos, sizeof(float), 3);
            deserializer.Read(out this.vel, sizeof(float), 3);
            deserializer.Read(out this.force, sizeof(float), 3);
            deserializer.Read(out this.pos_art, sizeof(float), 6);
            deserializer.Read(out this.vel_art, sizeof(float), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pos_x);
            serializer.Write(this.pos_y);
            serializer.Write(this.pos_z);
            serializer.Write(this.times);
            serializer.Write(this.pos);
            serializer.Write(this.vel);
            serializer.Write(this.force);
            serializer.Write(this.pos_art);
            serializer.Write(this.vel_art);
        }

        public override string ToString()
        {
            return "UnityPositionMsg: " +
            "\npos_x: " + pos_x.ToString() +
            "\npos_y: " + pos_y.ToString() +
            "\npos_z: " + pos_z.ToString() +
            "\ntimes: " + times.ToString() +
            "\npos: " + System.String.Join(", ", pos.ToList()) +
            "\nvel: " + System.String.Join(", ", vel.ToList()) +
            "\nforce: " + System.String.Join(", ", force.ToList()) +
            "\npos_art: " + System.String.Join(", ", pos_art.ToList()) +
            "\nvel_art: " + System.String.Join(", ", vel_art.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
