//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class UnityCollisionMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/UnityCollision";
        public override string RosMessageName => k_RosMessageName;

        public bool collision;

        public UnityCollisionMsg()
        {
            this.collision = false;
        }

        public UnityCollisionMsg(bool collision)
        {
            this.collision = collision;
        }

        public static UnityCollisionMsg Deserialize(MessageDeserializer deserializer) => new UnityCollisionMsg(deserializer);

        private UnityCollisionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.collision);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.collision);
        }

        public override string ToString()
        {
            return "UnityCollisionMsg: " +
            "\ncollision: " + collision.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
